spring.application.name=smart-inbox-guardian-backend
spring.datasource.url=jdbc:mysql://localhost:3306/smart_inbox_guardian
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update